[package]
name = "wallet"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wallet"
path = "src/main.rs"

[lib]
name = "xparq_wallet"
path = "src/lib.rs"

[features]
default = ["mainnet"]
mainnet = ["xparq/mainnet"]
testnet = ["xparq/testnet"]
devnet = ["xparq/devnet"]
sqisign-blockchain-test = ["xparq/sqisign-blockchain-test"]

[dependencies]
argon2.workspace = true
bip39.workspace = true
chacha20poly1305.workspace = true
getrandom.workspace = true
hex.workspace = true
xparq.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
zeroize.workspace = true
