[workspace]
resolver = "3"
members = [
    "crates/primitives",
    "crates/consensus",
    "crates/wxpq",
    "crates/tokens",
    "crates/native-token-program",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
license = "MIT"
repository = "https://github.com/XPARQ-Labs/XPARQ"

[workspace.dependencies]
sha3 = { version = "0.12.0", default-features = false, path = "../depend/sha3/sha3" }
bech32 = { version = "0.12.0", default-features = false, features = ["alloc"] }
borsh = { version = "1.5", features = ["derive"] }
rand_10 = { package = "rand", version = "0.10.0", path = "../depend/sqisign/rand-0.10" }
thiserror = "2"
xparq-sqisign = { version = "0.1.0", path = "../depend/sqisign/sqisign-rs" }

xparq-sidechain-primitives = { path = "crates/primitives" }
xparq-sidechain-wxpq = { path = "crates/wxpq" }
xparq-sidechain-tokens = { path = "crates/tokens" }
