[package]
name = "kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "xparq"

[features]
default = ["mainnet"]
mainnet = ["xparq-crypto/mainnet"]
testnet = ["xparq-crypto/testnet"]
devnet = ["xparq-crypto/devnet"]
sqisign-blockchain-test = ["devnet"]
falcon-candidate = ["xparq-crypto/falcon-candidate"]

[dependencies]
borsh.workspace = true
sha3.workspace = true
static_assertions.workspace = true
xparq-crypto.workspace = true
xparq-extension.workspace = true
