[package]
name = "xparq-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[[bin]]
name = "xparq-node"
path = "src/main.rs"

[features]
default = ["mainnet"]
mainnet = ["xparq/mainnet"]
testnet = ["xparq/testnet"]
devnet = ["xparq/devnet"]
sqisign-blockchain-test = ["xparq/sqisign-blockchain-test"]

[dependencies]
axum.workspace = true
axum-server.workspace = true
async-trait.workspace = true
borsh.workspace = true
ctrlc.workspace = true
futures-util.workspace = true
hex.workspace = true
igd-next.workspace = true
lmdb.workspace = true
libp2p.workspace = true
xparq.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
socket2.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tower.workspace = true
tower-http.workspace = true
zeroize.workspace = true

[build-dependencies]
protoc-bin-vendored.workspace = true
tonic-prost-build.workspace = true
