[package]
name = "xparq-blockchain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["mainnet"]
mainnet = ["xparq-coin/mainnet", "xparq-crypto/mainnet", "xparq-transaction/mainnet"]
testnet = ["xparq-coin/testnet", "xparq-crypto/testnet", "xparq-transaction/testnet"]
devnet = ["xparq-coin/devnet", "xparq-crypto/devnet", "xparq-transaction/devnet"]
sqisign-blockchain-test = ["xparq-coin/sqisign-blockchain-test", "xparq-crypto/sqisign-blockchain-test"]

[dependencies]
xparq-common.workspace = true
xparq-crypto.workspace = true
xparq-coin.workspace = true
xparq-transaction.workspace = true
borsh.workspace = true
static_assertions.workspace = true
