[package]
name = "xparq-transaction"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/mod.rs"

[features]
default = ["mainnet"]
mainnet = ["xparq-crypto/mainnet", "xparq-coin/mainnet"]
testnet = ["xparq-crypto/testnet", "xparq-coin/testnet"]
devnet = ["xparq-crypto/devnet", "xparq-coin/devnet"]

[dependencies]
xparq-common.workspace = true
xparq-crypto.workspace = true
xparq-coin.workspace = true
xparq-asset.workspace = true
borsh.workspace = true
