[package]
name = "xparq-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["mainnet"]
mainnet = []
testnet = []
devnet = ["sqisign-blockchain-test"]
sqisign-blockchain-test = ["dep:rand_10", "dep:sqisign_rs", "dep:chacha20"]

[dependencies]
xparq-common.workspace = true
sha3.workspace = true
ml_dsa.workspace = true
sqisign_rs = { workspace = true, optional = true }
rand_10 = { workspace = true, optional = true }
chacha20 = { workspace = true, optional = true }
borsh.workspace = true
serde.workspace = true
bech32.workspace = true
zeroize.workspace = true
argon2.workspace = true
getrandom.workspace = true
static_assertions.workspace = true
